### ISSUE TITLE
Install Gentoo

### ISSUE THREAD

**Issue by allbombson** [Austcool-Walker/GoddessBlackHeartBot#1]
I have the xmpp setup and and ircd please install gentoo and stop using python

**Comment by Austcool-Walker** [comment]
@allbombson this isn't vaild bug report; GoodBye Presses Black Button. Good Day! 🤪

**Comment by Bobbbay** [comment]
NOOO But this is issue #1, lucky number! 

Btw, this is completely possible if you create a directory and chroot to it. Definitely something to look into!

**Comment by Austcool-Walker** [comment]
@allbombson @Bobbbay if you have a legitimate issue related to blackheart then you can open an issue here otherwise I'll just be blocking and closing the issue since it legitimate has zero to do with blackheart and is more becoming muti-platform harassment.
